language: php

php:
  - 5.4
  - 5.5
  - hhvm

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit --coverage-text tests
